### ISSUE TITLE
missing imports

### ISSUE THREAD

**Issue by smn17** [FabianFriedrich/Text2Process#1]
It is not possible to compile this project, because of missing imports. It seems that an older version of the Process Editor is needed (which is not available on the web page).
Is it possible to get the needed version?

**Comment by FabianFriedrich** [comment]
Hi SMN,

Sorry for the long lead time.
I finally looked into it and added all needed libraries and runtime resources.

Please let me know if you face any other issue, but you should be able to run the application now.
